// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
namespace FatturaElettronica_PRISM_WPF_V2.Models;

public partial class Fattura
{
    public string IdFattura { get; set; }

    public string Tipo { get; set; }

    public string NomeFile { get; set; }

    public string IdFornitore { get; set; }

    public string IdCliente { get; set; }

    public string Numero { get; set; }

    public string Anno { get; set; }

    public string Mese { get; set; }

    public string Giorno { get; set; }

    public decimal Imponibile { get; set; }

    public decimal? Imposta { get; set; }

    public decimal Importo { get; set; }

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual Fornitore IdFornitoreNavigation { get; set; }

    public virtual ObservableCollection<RigaDettaglio> RigheDettaglioFatturaOC { get; set; } = new ObservableCollection<RigaDettaglio>();
}