// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#pragma warning disable CS8669

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
namespace FatturaElettronica_PRISM_WPF_V2.Models;

public partial class Fornitore
{
    public string PartitaIVA { get; set; }

    public string Denominazione { get; set; }

    public string? Provincia { get; set; }

    public string? Comune { get; set; }

    public string? CAP { get; set; }

    public string? Indirizzo { get; set; }

    public virtual ObservableCollection<Fattura> FattureFornitoreOC { get; set; } = new ObservableCollection<Fattura>();
}