// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#pragma warning disable CS8669 

using System;
using System.Collections.Generic;
namespace FatturaElettronica_PRISM_WPF_V2.Models;

public partial class RigaDettaglio
{
    public string IdRigaDettaglio { get; set; }

    public string IdFattura { get; set; }

    public string? CodiceArticolo { get; set; }

    public string? DescrizioneArticolo { get; set; }

    public string? UnitàMisura { get; set; }

    public decimal Quantità { get; set; }

    public decimal PrezzoUnitario { get; set; }

    public decimal Imponibile { get; set; }

    public int? AliquotaIva { get; set; }

    public decimal? Imposta { get; set; }

    public decimal PrezzoTotale { get; set; }

    public virtual Fattura IdFatturaNavigation { get; set; }
}